---
- include_vars     : "{{ item }}"
  with_first_found :
   - "{{ ansible_os_family }}.yml"
   - "default.yml"

# Setup all the variables that are used in the playbook
- include: set_vars.yml

# Import data into Tile DB and Meta DB
- include: data.yml

# Setup the webserver configuration files
- include: server_config.yml
