---
- name  : Setup the webserver
  shell : >
    {{store_dir}}/web/setup_webserver.py 
    --port {{webserver_port}} 
    --socket_path {{uwsgi_socket_path}} 
    --array_name {{array_name}}
    --service_directory {{system_services_path}}
    --service_extension {{system_services_extension}}
    --nginx_conf_directory {{nginx_conf_path}}
    --skip_services
  become      : yes
  become_user : "{{owner_user_name}}"

- name    : reload systemctl
  command : systemctl daemon-reload
  when    : ansible_os_family == 'RedHat'

- name    : "restart ga4gh_{{array_name}}"
  service :
    name    : "ga4gh_{{array_name}}"
    enabled : yes
    state   : restarted
  notify   : restart nginx
