# The MIT License (MIT)
# Copyright (c) 2016 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of 
# this software and associated documentation files (the "Software"), to deal in 
# the Software without restriction, including without limitation the rights to 
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of 
# the Software, and to permit persons to whom the Software is furnished to do so, 
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS 
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

---
# Update genomics DB variables
- name     : Set variable array_name
  set_fact : array_name={{default_array_name}}
  when     : array_name is not defined

# Update web server variables
- name     : Set variable system_services_path
  set_fact : system_services_path={{default_system_services_path}}
  when     : system_services_path is not defined

- name     : Set variable system_services_extension
  set_fact : system_services_extension={{default_system_services_extension}}
  when     : system_services_extension is not defined

- name     : Set variable webserver_port
  set_fact : webserver_port={{default_webserver_port}}
  when     : webserver_port is not defined

- name     : Set variable import_path
  set_fact : 
    import_path     : "{{store_dir}}/test/data/"
    skip_data_rsync : "true"
  when     : import_path is not defined

- name     : Set variable mappingdb_file
  set_fact : mappingdb_file={{default_mappingdb_file}}
  when     : mappingdb_file is not defined

- name     : Set variable callset_mapping_file
  set_fact : callset_mapping_file={{default_callset_mapping_file}}
  when     : callset_mapping_file is not defined

- name     : Set variable vid_mapping_file
  set_fact : vid_mapping_file={{default_vid_mapping_file}}
  when     : vid_mapping_file is not defined

- name     : Set variable size_per_column_partition
  set_fact : size_per_column_partition={{default_size_per_column_partition}}
  when     : size_per_column_partition is not defined

- name     : Set variable delete_and_create_tiledb_array
  set_fact : delete_and_create_tiledb_array={{default_delete_and_create_tiledb_array}}
  when     : delete_and_create_tiledb_array is not defined

- name     : Set variable lb_callset_row_idx
  set_fact : lb_callset_row_idx={{default_lb_callset_row_id}}
  when     : lb_callset_row_idx is not defined
