# vi: set ft=yaml.jinja :

---

- name: Remove EPEL release rpm if previously installed by the Ansible Galaxy EPEL role
  yum:
    name: epel-release
    state: absent
  when: ansible_os_family == "RedHat"
  notify: yum update cache

- name: Remove EPEL repo file installed by older version of this role or the Ansible Galaxy EPEL role
  file:
    path: /etc/yum.repos.d/epel-release.repo
    state: absent
  when: ansible_os_family == "RedHat"
  notify: yum update cache

- name: Install EPEL RPM
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    disable_gpg_check: yes
    state: present
  tags:
    - install
  when: ansible_os_family == "RedHat" and
      ( ansible_distribution_major_version == "5" or
        ansible_distribution_major_version == "6" or
        ansible_distribution_major_version == "7" )
  notify: yum update cache

- name: Force flush handlers (may be invoked as dependency)
  meta: flush_handlers
