---
- name     : Set ssh_key_file
  set_fact : ssh_key_file=id_rsa

- name     : Set ssh_key_dir
  set_fact : ssh_key_dir=/home/travis/.ssh

- name     : Clear ssh_proxy
  set_fact : default_ssh_proxy=""

- name       : Install lcov package for ci environment
  action     : "{{ansible_pkg_mgr}} name=lcov state=present"

- name     : Set default_library_build to debug-coverage
  set_fact : default_library_build=debug-coverage
