---
- name     : Set fact meta_db_name
  set_fact : meta_db_name={{default_meta_db_name}}
  when     : meta_db_name is not defined

- name            : Setup the owner for the db
  postgresql_user :
    name            : "{{owner_user_name}}"
    role_attr_flags : "CREATEDB"
    priv            : ALL
  become          : yes
  become_user     : postgres

- name          : Create the postgres db
  postgresql_db : 
    name  : "{{meta_db_name}}"
    owner : "{{owner_user_name}}"
  become        : yes
  become_user   : "{{owner_user_name}}"

- name            : Setup the reader/client for the db
  postgresql_user : 
    db              : "{{meta_db_name}}"
    name            : "{{client_user_name}}"
    role_attr_flags : "NOSUPERUSER,NOCREATEDB"
  become          : yes
  become_user     : postgres
  when            : client_user_name != owner_user_name
