---
- name     : Set fact ssh_key_file
  set_fact : ssh_key_file={{default_ssh_key_file}}
  when     : ssh_key_file is not defined

- name     : Set fact ssh_key_dir
  set_fact : ssh_key_dir={{default_ssh_key_dir}}
  when     : ssh_key_dir is not defined

- name     : Set fact ssh_key_dest_dir
  set_fact : ssh_key_dest_dir=/home/{{owner_user_name}}/.ssh
  when     : ssh_key_dest_dir is not defined

- name     : set fact ssh_key
  set_fact : ssh_key={{ssh_key_dest_dir}}/{{ssh_key_file}}

- name     : Set fact ssh_proxy
  set_fact : ssh_proxy="{{default_ssh_proxy}}"
  when     : ssh_proxy is not defined

- name : Fix permissions on the .ssh folder if necessary
  file :
    path    : "{{ssh_key_dest_dir}}"
    group   : "{{group_name}}"
    owner   : "{{owner_user_name}}"
    mode    : "0700"
    state   : directory
    recurse : yes

- name        : Copy ssh key into owner user's home
  synchronize : 
    src        : "{{ssh_key_dir}}/{{ssh_key_file}}"
    dest       : "{{ssh_key_dest_dir}}/"
    owner      : no
    group      : no
    rsync_path : "sudo rsync"

- name : Set the right permissions on the copied keys
  file :
    path    : "{{ssh_key}}"
    group   : "{{group_name}}"
    owner   : "{{owner_user_name}}"
    mode    : "0600"

- name       : Setup ssh config
  lineinfile :
    dest         : "{{ssh_key_dest_dir}}/config"
    line         : "Host github.com"
    insertbefore : BOF
    create       : yes
    group        : "{{group_name}}"
    owner        : "{{owner_user_name}}"
    mode         : "0600"

- name       : Setup ssh config with IdentityFile
  lineinfile :
    dest        : "{{ssh_key_dest_dir}}/config"
    line        : "    IdentityFile {{ssh_key}}"
    insertafter : "Host github.com"

- name       : Setup ssh config with proxy command 
  lineinfile :
    dest        : "{{ssh_key_dest_dir}}/config"
    line        : "    {{ssh_proxy}}"
    insertafter : "    IdentityFile {{ssh_key}}"
  when       : ssh_proxy is defined and ssh_proxy != ""

