# The MIT License (MIT)
# Copyright (c) 2016 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of 
# this software and associated documentation files (the "Software"), to deal in 
# the Software without restriction, including without limitation the rights to 
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of 
# the Software, and to permit persons to whom the Software is furnished to do so, 
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS 
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

---
- name     : Set fact templates_dir
  set_fact : templates_dir={{store_dir}}/web/templates
  when     : templates_dir is not defined

- name: Create the templates_dir directory with the right permissions
  file: 
    path  : "{{templates_dir}}"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"
    state : directory

- name     : Setup ga4gh ini template
  template :
    src   : ga4gh.ini.j2 
    dest  : "{{store_dir}}/web/templates/ga4gh.ini.template"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"

- name     : Setup ga4gh conf template
  template :
    src   : ga4gh.conf.j2 
    dest  : "{{store_dir}}/web/templates/ga4gh.cfg.template"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"

- name     : Setup ga4gh service template
  template :
    src  : "ga4gh.service.{{ansible_os_family}}.j2"
    dest : "{{store_dir}}/web/templates/ga4gh.{{template_system_services_extension}}.template"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"

- name     : Setup nginx conf file template
  template :
    src  : nginx.conf.j2 
    dest : "{{store_dir}}/web/templates/nginx_ga4gh.conf.template"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"

- name     : Setup tiledb_loader template
  template :
    src  : tiledb_loader.json.j2
    dest : "{{store_dir}}/utils/example_configs/tiledb_loader.json"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"

- name     : Setup load_to_tile.cfg template
  template :
    src  : load_to_tile.cfg.j2
    dest : "{{store_dir}}/utils/example_configs/load_to_tile.cfg"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"

- name: fix path on the callset_mapping_file
  replace:
    dest: "{{store_dir}}/test/data/test.callset_mapping"
    regexp: '\/path'
    replace: "{{store_dir}}/test/data"
