---
- name     : Set variable is_clean_compile
  set_fact : is_clean_compile={{default_is_clean_compile}}
  when     : is_clean_compile is not defined

- name    : Clean build search library
  command : "make clean"
  args    :
    chdir : "{{store_dir}}/search_library"
  when    : is_clean_compile

- name     : Set variable library_build
  set_fact : library_build={{default_library_build}}
  when     : library_build is not defined

- name: set make_cmd_line variable
  set_fact: make_cmd_line="make BUILD={{library_build}} GENOMICSDB_DIR={{GenomicsDB_dir}}"
  when: libcsv_path is not defined

- name: update libcsv_path
  set_fact: make_cmd_line="make BUILD={{library_build}} GENOMICSDB_DIR={{GenomicsDB_dir}} LIBCSV_DIR={{libcsv_path}}"
  when: libcsv_path is defined

- name    : Compile search library
  command : "{{make_cmd_line}}"
  args        :
    chdir   : "{{store_dir}}/search_library"
    creates : "{{store_dir}}/search_library/lib/libquery.so"
  environment :
    PATH            : "{{env_path}}:{{ansible_env.PATH}}"
    LD_LIBRARY_PATH : "{{env_ld_library_path}}"
  become      : yes
  become_user : "{{owner_user_name}}"

- name: Create the Tile DB workspace directory with the right permissions
  command : "{{GenomicsDB_dir}}/bin/create_tiledb_workspace {{workspace_dir}}"
  args        :
    creates : "{{workspace_dir}}"
  environment :
    PATH            : "{{env_path}}:{{ansible_env.PATH}}"
    LD_LIBRARY_PATH : "{{env_ld_library_path}}"
  become      : yes
  become_user : "{{owner_user_name}}"
