# The MIT License (MIT)
# Copyright (c) 2016 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of 
# this software and associated documentation files (the "Software"), to deal in 
# the Software without restriction, including without limitation the rights to 
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of 
# the Software, and to permit persons to whom the Software is furnished to do so, 
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS 
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# vi: set ft=yaml.jinja :

---
- include_vars: ../../postgresql-server/defaults/main.yml

- template:
    src:   etc/yum.repos.d/pgdg.repo.j2
    dest: /etc/yum.repos.d/pgdg.repo
    owner: root
    group: root
    mode: "0644"
  when: ansible_os_family == "RedHat" and
      ( ansible_distribution_major_version == "5" or
        ansible_distribution_major_version == "6" or
        ansible_distribution_major_version == "7" )

- name: temp key fix
  command: "rpmkeys --import http://apt.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-{{ postgresql_version|default(postgresql_default_version)|replace('.', '') }}"
  when: ansible_os_family == "RedHat" and
      ( ansible_distribution_major_version == "5" or
        ansible_distribution_major_version == "6" or
        ansible_distribution_major_version == "7" )

- apt_key:
    state: present
    keyserver: pgp.mit.edu
    id: ACCC4CF8
  when: ansible_os_family == "Debian"

- copy:
    src:   etc/apt/preferences.d/pgdg.pref
    dest: /etc/apt/preferences.d/pgdg.pref
    owner: root
    group: root
    mode: "0644"
  when: ansible_os_family == "Debian"

- apt_repository:
    state: present
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    update_cache: yes
  when: ansible_os_family == "Debian"
