---

- name: Install SCL repo
  yum:
      name: centos-release-scl
      state: latest
  notify: yum update cache
  when: ansible_os_family == "RedHat" and install_scl_repo|is_defined_true

- name: Remove SCL repo
  yum:
      name: centos-release-scl
      state: absent
  notify: yum update cache
  when: ansible_os_family == "RedHat" and not(install_scl_repo|is_defined_true)

- name: Force handlers (may be invoked as dependency)
  meta: flush_handlers
