---
# GCC Defaults
gcc_version : 4.9.3
gcc_prefix  : /opt/gcc-{{gcc_version}}

# Meta DB Defaults
default_meta_db_name   : metadb
default_metadb_adapter : postgresql+psycopg2

# Group and Users - default group, user name and passwords for read (client) and read/write (owner) permissions
default_group_name       : ga4gh
default_client_user_name : ga4gh_client
default_owner_user_name  : ga4gh_writer
default_permissions      : "u=rwx,g=rx,o=x"

# Directories
default_variantdb_dir    : /home/variantdb
default_workspace_name   : DB

# ssh variables
default_ssh_key_file : id_git_nopass
default_ssh_key_dir  : /home/user/.ssh
# Set default ssh_proxy to none, users can override with ssh_proxy
default_ssh_proxy    : ""
# default_ssh_proxy    : "ProxyCommand ncat --proxy-type socks4 --proxy 192.168.100.1:2001 %h %p"

# Tile DB/Search Library 
default_mpi_path         : /usr/lib64/openmpi
default_mpi_runner       : mpirun
default_is_clean_compile : true
default_store_branch     : HEAD
default_library_build    : release

template_system_services_extension : service
# Template overrides
template_array_name     : "<Array_Name>"
template_uwsgi_socket   : "<uwsgi_socket_path>"
template_webserver_port : "<PORT>"
